# Generated by Django 3.1.5 on 2021-03-30 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0002_auto_20210329_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeling',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
