# Generated by Django 3.1.5 on 2021-04-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0003_modeling_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('art_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
