# Generated by Django 3.1.5 on 2021-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0005_coading'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeling',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
