# Generated by Django 3.1.5 on 2021-04-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0008_aprojects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprojects',
            old_name='project_img',
            new_name='aproject_img',
        ),
    ]
