# Generated by Django 3.1.5 on 2021-05-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0010_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_des',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.TextField()),
            ],
        ),
    ]
